### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by AhmadHRai** [hsul4n/dart-clip#1]
after commit `910b96b6161a6f5cfbe90dfe156db18d88eeae2d` the uploaded images quality were unreadable by human eye and not recognized by ocr

**Comment by hsul4n** [comment]
@AhmadHRai Please make sure to increase `quality` value in `ImageClipField` which found in https://github.com/hsul4n/dart-clip/blob/596d724a7d06f7ed7e70b0d6d0cbac1ad4b00a05/lib/src/widgets/image_clip_field.dart#L27
